spring:
  profiles:
    include:
      - domain
      - application
      - infra-opensearch
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
    com:
      kidsworld:
        api: info

server:
  port: 8080

  # jpa 관련 설정
  jpa:
    output:
      ansi:
        enabled: always
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  # Postgres testcontainer
  datasource:
    url: jdbc:tc:postgresql:{version}:///{dbname}?TC_INITSCRIPT=file:src/test/resources/schema.sql
    username: Username
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver